{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":241755430,"authorName":"Don Ferguson","from":"&quot;Don Ferguson&quot; &lt;donald.ferguson@...&gt;","profile":"dferguson001","replyTo":"LIST","senderId":"2YCmnB0sulwOqQvlc3iPjN7-XoRwrm6v8ZtUNrRTZRjKQzez1S-D7SWpQjftIzRagHocRda8EKp-5c4MZLd6vHwH7E6MdafOXvQnZufUoPiPthgY","spamInfo":{"isSpam":false,"reason":"12"},"subject":"Trouble getting started","postDate":"1129908775","msgId":1011,"canDelete":false,"contentTrasformed":false,"systemMessage":true,"headers":{"messageIdInHeader":"PGRqYjFuNytvbXNrQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":1013,"prevInTime":1010,"nextInTime":1012,"topicId":1011,"numMessagesInTopic":2,"msgSnippet":"Just installed Cantera and Python along with the numeric.  When I try and run tut1.py I receive the following error.  Running under Windows 2000.  Any","rawEmail":"Return-Path: &lt;donald.ferguson@...&gt;\r\nReceived: (qmail 7008 invoked from network); 21 Oct 2005 16:12:46 -0000\r\nReceived: from unknown (66.218.66.172)\n  by m24.grp.scd.yahoo.com with QMQP; 21 Oct 2005 16:12:46 -0000\r\nReceived: from unknown (HELO n18a.bulk.scd.yahoo.com) (66.94.237.47)\n  by mta4.grp.scd.yahoo.com with SMTP; 21 Oct 2005 16:12:46 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [66.218.66.59] by n18.bulk.scd.yahoo.com with NNFMP; 21 Oct 2005 16:12:26 -0000\r\nReceived: from [66.218.66.86] by mailer8.bulk.scd.yahoo.com with NNFMP; 21 Oct 2005 16:12:26 -0000\r\nX-Sender: donald.ferguson@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 22007 invoked from network); 21 Oct 2005 15:33:21 -0000\r\nReceived: from unknown (66.218.66.217)\n  by m35.grp.scd.yahoo.com with QMQP; 21 Oct 2005 15:33:21 -0000\r\nReceived: from unknown (HELO n18a.bulk.scd.yahoo.com) (66.94.237.47)\n  by mta2.grp.scd.yahoo.com with SMTP; 21 Oct 2005 15:33:21 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [66.218.66.58] by n18.bulk.scd.yahoo.com with NNFMP; 21 Oct 2005 15:32:56 -0000\r\nReceived: from [66.218.66.88] by mailer7.bulk.scd.yahoo.com with NNFMP; 21 Oct 2005 15:32:56 -0000\r\nDate: Fri, 21 Oct 2005 15:32:55 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;djb1n7+omsk@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-system\r\nX-eGroups-Msg-Info: 1:12:0:0\r\nFrom: &quot;Don Ferguson&quot; &lt;donald.ferguson@...&gt;\r\nSubject: Trouble getting started\r\nX-Yahoo-Group-Post: member; u=241755430; y=Ez_W9fTPpXRT4k0kjm136ulyDGbbatDca944RbnuxaclFh2crrBZ\r\nX-Yahoo-Profile: dferguson001\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 21 Oct 2005 16:12:25 -0000\r\n\r\nJust installed Cantera and Python along with the numeric.  When I try \nand =\r\nrun tut1.py I receive the following error.  Running under Windows \n2000.  A=\r\nny thoughts? \n\n\nTraceback (most recent call last):\n  File &quot;C:&#92;cantera16&#92;tut=\r\norials&#92;Python&#92;tut1.py&quot;, line 13, in -toplevel-\n    from Cantera import *\n  =\r\nFile &quot;C:&#92;Python24&#92;Lib&#92;site-packages&#92;Cantera&#92;__init__.py&quot;, line 7, in -\ntopl=\r\nevel-\n    import _cantera\nImportError: No module named numarray.libnumeric\n=\r\n\n\nthanks,\nDon Ferguson\n\n\n\n\n\n\n"}}