{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":241540864,"authorName":"jocie_squirl","from":"&quot;jocie_squirl&quot; &lt;jocie_squirl@...&gt;","profile":"jocie_squirl","replyTo":"LIST","senderId":"HxoF0Iv8WJMnkSqJgr8P85T0tbqtdfawjEVrY77-w9B1o6LnXOQv55G4CZR3yguGJjwz666OyuzNXuUl1BKjqI-SMoica7LD1cQMtPy-SV0","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Python with Mac OS X","postDate":"1150760161","msgId":1256,"canDelete":false,"contentTrasformed":false,"systemMessage":true,"headers":{"messageIdInHeader":"PGU3N2NkMStkbXZhQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":1257,"prevInTime":1255,"nextInTime":1257,"topicId":1256,"numMessagesInTopic":2,"msgSnippet":"When I am attempting to update my cantera from the CVS site, I get the following error message when I run the ./configure: ERROR: PYTHON_PACKAGE variable,  ,","rawEmail":"Return-Path: &lt;jocie_squirl@...&gt;\r\nReceived: (qmail 95581 invoked from network); 21 Jun 2006 03:04:51 -0000\r\nReceived: from unknown (66.218.66.167)\n  by m33.grp.scd.yahoo.com with QMQP; 21 Jun 2006 03:04:51 -0000\r\nReceived: from unknown (HELO n22a.bullet.scd.yahoo.com) (66.94.237.51)\n  by mta6.grp.scd.yahoo.com with SMTP; 21 Jun 2006 03:04:51 -0000\r\nReceived: from [66.218.69.3] by n22.bullet.scd.yahoo.com with NNFMP; 21 Jun 2006 03:04:51 -0000\r\nReceived: from [66.218.66.79] by t3.bullet.scd.yahoo.com with NNFMP; 21 Jun 2006 03:04:51 -0000\r\nX-Sender: jocie_squirl@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 14492 invoked from network); 19 Jun 2006 23:36:05 -0000\r\nReceived: from unknown (66.218.66.216)\n  by m28.grp.scd.yahoo.com with QMQP; 19 Jun 2006 23:36:05 -0000\r\nReceived: from unknown (HELO n30a.bullet.scd.yahoo.com) (209.73.160.88)\n  by mta1.grp.scd.yahoo.com with SMTP; 19 Jun 2006 23:36:05 -0000\r\nReceived: from [66.218.69.4] by n30.bullet.scd.yahoo.com with NNFMP; 19 Jun 2006 23:36:02 -0000\r\nReceived: from [66.218.66.86] by t4.bullet.scd.yahoo.com with NNFMP; 19 Jun 2006 23:36:01 -0000\r\nDate: Mon, 19 Jun 2006 23:36:01 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;e77cd1+dmva@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-system\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;jocie_squirl&quot; &lt;jocie_squirl@...&gt;\r\nSubject: Python with Mac OS X\r\nX-Yahoo-Group-Post: member; u=241540864; y=wYunnBYbQKbEGNPqaEBUQUbseFLeMCtibtzYsYJGf9Y9n9vZg-ud\r\nX-Yahoo-Profile: jocie_squirl\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 21 Jun 2006 03:04:50 -0000\r\n\r\nWhen I am attempting to update my cantera from the CVS site, I get the\nfoll=\r\nowing error message when I run the ./configure:\n\nERROR: PYTHON_PACKAGE vari=\r\nable,  , is not understood. Use:\n       full, default, minimal, or none\n\nCa=\r\nn someone please advise what I need to do to correct this so it\nconfigures =\r\ncorrectly?\nThanks so much,\nJocelyn\n\n\n\n\n\n\n"}}