{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":161379174,"authorName":"galliumnitrid","from":"&quot;galliumnitrid&quot; &lt;atakan@...&gt;","profile":"galliumnitrid","replyTo":"LIST","senderId":"vgDp0mN_pLbzqyDbYxpNf756xZ5xCsVYTaF71BJEufDrto-yr3LEnjP22zQAXlYPWjE_WtmE0tX1VC92kGDFKY9zz64Qk7DDCmtD4d_Imw","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Error in cantera installation","postDate":"1064921987","msgId":200,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGJsYnEyMytsM251QGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":203,"prevInTime":199,"nextInTime":201,"topicId":200,"numMessagesInTopic":4,"msgSnippet":"Dear Dr. Goodwin, I just installed cantera(1.5) and python on my windows computer. As I wanted to test it, I received the following error message: Traceback","rawEmail":"Return-Path: &lt;atakan@...&gt;\r\nReceived: (qmail 33201 invoked from network); 30 Sep 2003 13:25:46 -0000\r\nReceived: from unknown (66.218.66.167)\n  by m14.grp.scd.yahoo.com with QMQP; 30 Sep 2003 13:25:46 -0000\r\nReceived: from unknown (HELO n23.grp.scd.yahoo.com) (66.218.66.79)\n  by mta6.grp.scd.yahoo.com with SMTP; 30 Sep 2003 13:25:45 -0000\r\nX-eGroups-Return: atakan@...\r\nReceived: from [66.218.67.166] by n23.grp.scd.yahoo.com with NNFMP; 30 Sep 2003 13:25:45 -0000\r\nX-Sender: atakan@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 33010 invoked from network); 30 Sep 2003 11:39:48 -0000\r\nReceived: from unknown (66.218.66.216)\n  by m1.grp.scd.yahoo.com with QMQP; 30 Sep 2003 11:39:48 -0000\r\nReceived: from unknown (HELO n23.grp.scd.yahoo.com) (66.218.66.79)\n  by mta1.grp.scd.yahoo.com with SMTP; 30 Sep 2003 11:39:48 -0000\r\nReceived: from [66.218.67.187] by n23.grp.scd.yahoo.com with NNFMP; 30 Sep 2003 11:39:47 -0000\r\nDate: Tue, 30 Sep 2003 11:39:47 -0000\r\nTo: cantera@yahoogroups.com\r\nSubject: Error in cantera installation\r\nMessage-ID: &lt;blbq23+l3nu@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 1002\r\nX-Mailer: Yahoo Groups Message Poster\r\nFrom: &quot;galliumnitrid&quot; &lt;atakan@...&gt;\r\nX-Yahoo-Group-Post: member; u=161379174\r\nX-Yahoo-Profile: galliumnitrid\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 30 Sep 2003 13:25:44 -0000\r\n\r\nDear Dr. Goodwin,\nI just installed cantera(1.5) and python on my windows computer.\nAs I wanted to test it, I received the following error message:\nTraceback (most recent call last):\n  \nFile &quot;D:&#92;Programme&#92;ThermoPrgsKlein&#92;CANTERA&#92;demos&#92;Python&#92;reactor1.py&quot;, \nline 6, in -toplevel-\n    from Cantera import *\n  File &quot;D:&#92;PROGRA~1&#92;KINETICS&#92;Python&#92;Cantera&#92;__init__.py&quot;, line 7, in -\ntoplevel-\n    from gases import *\n  File &quot;D:&#92;PROGRA~1&#92;KINETICS&#92;Python&#92;Cantera&#92;gases.py&quot;, line 4, in -\ntoplevel-\n    from solution import Solution\n  File &quot;D:&#92;PROGRA~1&#92;KINETICS&#92;Python&#92;Cantera&#92;solution.py&quot;, line 8, in -\ntoplevel-\n    from ThermoPhase import ThermoPhase\n  File &quot;D:&#92;PROGRA~1&#92;KINETICS&#92;Python&#92;Cantera&#92;ThermoPhase.py&quot;, line 4, \nin -toplevel-\n    from Cantera.Phase import Phase\n  File &quot;D:&#92;PROGRA~1&#92;KINETICS&#92;Python&#92;Cantera&#92;Phase.py&quot;, line 7, in -\ntoplevel-\n    import _cantera\nImportError: No module named _cantera\n\nI found a file named _cantera.pyd but none called _cantera.py\n\nCould you help me?\nThank you!\nB. Atakan\n\n\n\n"}}