{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":122770107,"authorName":"usenechal","from":"&quot;usenechal&quot; &lt;senechal@...-dresden.de&gt;","profile":"usenechal","replyTo":"LIST","senderId":"UBPZg_awZNOTPMhKNLsZXqvPEhY3SDyr005faRRapPe7PtgOJvn2sV3gogcyrjUncArmDn_47TXpQxrAVn97OGWFj5d4L3fk8mnEphG3_4pwYw","spamInfo":{"isSpam":false,"reason":"0"},"subject":"python installation trouble","postDate":"1079376587","msgId":318,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGMzNHRzYis5N281QGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":319,"prevInTime":317,"nextInTime":319,"topicId":318,"numMessagesInTopic":3,"msgSnippet":"Dear Prof. Goodwin, I just installed Cantera153.msi and tried the reactor1.py for testing ... Traceback (most recent call last): File","rawEmail":"Return-Path: &lt;senechal@...-dresden.de&gt;\r\nX-Sender: senechal@...-dresden.de\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 55294 invoked from network); 15 Mar 2004 18:49:57 -0000\r\nReceived: from unknown (66.218.66.217)\n  by m10.grp.scd.yahoo.com with QMQP; 15 Mar 2004 18:49:57 -0000\r\nReceived: from unknown (HELO n31.grp.scd.yahoo.com) (66.218.66.99)\n  by mta2.grp.scd.yahoo.com with SMTP; 15 Mar 2004 18:49:56 -0000\r\nReceived: from [66.218.66.112] by n31.grp.scd.yahoo.com with NNFMP; 15 Mar 2004 18:49:48 -0000\r\nDate: Mon, 15 Mar 2004 18:49:47 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;c34tsb+97o5@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 1850\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-eGroups-Remote-IP: 66.218.66.99\r\nFrom: &quot;usenechal&quot; &lt;senechal@...-dresden.de&gt;\r\nSubject: python installation trouble\r\nX-Yahoo-Group-Post: member; u=122770107\r\nX-Yahoo-Profile: usenechal\r\n\r\nDear Prof. Goodwin,\n\nI just installed Cantera153.msi and tried the reactor1.py for testing\n (I changed  I get an error :\n\n------------start error message 1-----------------------------\nTraceback (most recent call last):\n  File &quot;C:&#92;Programme&#92;Cantera153&#92;demos&#92;Python&#92;reactor1.py&quot;, line 11, in ?\n    gri3 = GRI30()\n  File &quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;gases.py&quot;, line\n33, in GRI30\n    return Solution(src=&quot;gri30.cti&quot;, id=&quot;gri30&quot;)\n  File &quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;solution.py&quot;,\nline 40, in __init__\n    root = XML.XML_Node(name = &#39;doc&#39;, src = src, preprocess = 1)\n  File &quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;XML.py&quot;, line\n35, in __init__\n    self._xml_id = _cantera.xml_get_XML_File(src)\nerror: \nProcedure: ct2ctml\nError:   could not convert input file to CTML\n command line was: c:/python23/python ./.cttmp.py&gt; ct2ctml.log 2&gt;&1\nError in Python installation.\n------------end error message 1-----------------------------\n\nWhen I modify the python-file to use\n&quot;gri3=IdealGasMix(&#39;gri30.xml&#39;,&#39;gri30&#39;)&quot; instead of &quot;gri3 = GRI30()&quot;\nthe error changes to:\n------------start error message 2-----------------------------\nTraceback (most recent call last):\n  File &quot;C:&#92;Programme&#92;Cantera153&#92;demos&#92;Python&#92;reactor1.py&quot;, line 15, in ?\n    gri3.equilibrate(&#39;HP&#39;)\n  File\n&quot;C:&#92;PROGRA~1&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;ThermoPhase.py&quot;, line\n256, in equilibrate\n    _cantera.thermo_equil(self._phase_id, ixy)\nerror: \nProcedure: ChemEquil\nError:   Temperature (3028.9 K) outside valid range of 300 K to 3000 K\n------------end error message 2-----------------------------\n\nThis temperature seems to be wrong compared with former\ncantera-releases, so what are these errors ? Manually compiling\ncantera for python (with cygwin) gives the same result (with python\nfor cygwin). Thanks a lot for your patience.\n\nbest regards\nulf\n\n\n"}}