{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":77491263,"authorName":"-Tom","from":"&quot;-Tom&quot; &lt;smithtp@...&gt;","profile":"smithtp","replyTo":"LIST","senderId":"BMDpSsw-wLAgyU9oEHr7p_n016eG5dj-vHiBfvyg7vfrzahDbIt4aB27mhB3bscpkyt0w0ZDBBTljzWIMYSmk5o","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Re: ct2ctml error","postDate":"1100850572","msgId":590,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGNuazhpYythYmlnQGVHcm91cHMuY29tPg==","inReplyToHeader":"PDY5NkQyMUFBLTM5REMtMTFEOS05NkVCLTAwMEQ5M0FFMjQxQUBjYWx0ZWNoLmVkdT4="},"prevInTopic":589,"nextInTopic":591,"prevInTime":589,"nextInTime":591,"topicId":588,"numMessagesInTopic":7,"msgSnippet":"Dr. Goodwin: Thank you for your prompt response. After review of your suggestion I investigated further.  The path specified in the error is not governed by","rawEmail":"Return-Path: &lt;smithtp@...&gt;\r\nX-Sender: smithtp@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 43128 invoked from network); 19 Nov 2004 07:49:39 -0000\r\nReceived: from unknown (66.218.66.166)\n  by m4.grp.scd.yahoo.com with QMQP; 19 Nov 2004 07:49:39 -0000\r\nReceived: from unknown (HELO n9a.bulk.scd.yahoo.com) (66.94.237.43)\n  by mta5.grp.scd.yahoo.com with SMTP; 19 Nov 2004 07:49:39 -0000\r\nReceived: from [66.218.69.2] by n9.bulk.scd.yahoo.com with NNFMP; 19 Nov 2004 07:49:39 -0000\r\nReceived: from [66.218.66.112] by mailer2.bulk.scd.yahoo.com with NNFMP; 19 Nov 2004 07:49:39 -0000\r\nDate: Fri, 19 Nov 2004 07:49:32 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;cnk8ic+abig@...&gt;\r\nIn-Reply-To: &lt;696D21AA-39DC-11D9-96EB-000D93AE241A@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 6985\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Remote-IP: 66.94.237.43\r\nFrom: &quot;-Tom&quot; &lt;smithtp@...&gt;\r\nSubject: Re: ct2ctml error\r\nX-Yahoo-Group-Post: member; u=77491263\r\nX-Yahoo-Profile: smithtp\r\n\r\n\nDr. Goodwin:\n\nThank you for your prompt response.\n\nAfter review of your suggestion I investigated further.  The path\nspecified in the error is not governed by the location of the demo\nfiles, but rather the location of my active temporary file.  This is\nset by the OS Environment Variables.  That said, I changed my TEMP \nvariables to point to c:&#92;tmpdir instead of in my long named profile\ndirectory.  However, this did not correct the error.\n\nIn which ever temp directory is specified there are 2 files generated\nbefore the error stops the program.   They are:\n.cttmp1100848520.pyw\n.check1100848520.pyw\nThe the contents and resulta of attempting to run these files is show\nbelow.  The .cttmp##.pyw file will successfully generate the file\ngri30.xml when initiated by the cmd prompt.   However the .check##.pyw\nerrors out.\n\nAre there additional steps I should attempt towards resolving this\nissue?  \n\nI appreaciate your assistance.\n\n-tom\n\n---Running gennerated files from DOS prompt --------start----------\nMicrosoft Windows XP [Version 5.1.2600]\n(C) Copyright 1985-2001 Microsoft Corp.\n\nC:&#92;Documents and Settings&#92;tps&gt;python c:&#92;tmpdir&#92;.cttmp1100848520.pyw\n\nC:&#92;Documents and Settings&#92;tps&gt;python c:&#92;tmpdir&#92;.check1100848520.pyw\nTraceback (most recent call last):\n  File &quot;c:&#92;tmpdir&#92;.check1100848520.pyw&quot;, line 1, in ?\n    from Cantera import ctml_writer\nImportError: cannot import name ctml_writer\n\nC:&#92;Documents and Settings&#92;tps&gt;\n----Running gennerated files from DOS prompt -----------end----------\n\n-------- Contents of .cttmp1100848520.pyw -----------------\nfrom ctml_writer import *\nimport sys, os, os.path\nfile = &quot;C:&#92;Program Files&#92;Common Files/Cantera/data/gri30.cti&quot;\nbase = os.path.basename(file)\nroot, ext = os.path.splitext(base)\ndataset(root)\nexecfile(file)\nwrite()\n-------------end .cttmp1100848520.pyw --------------------\n\n------- Contents of .check1100848520.pyw -------------\nfrom Cantera import ctml_writer\n------------End .check1100848520.pyw-------------------\n\n\n\n--- In cantera@yahoogroups.com, David Goodwin &lt;dgoodwin@c...&gt; wrote:\n&gt; Tom - I&#39;m not sure, but if I were to guess, I would guess that\nPython \n&gt; is not finding the temporary Python script Cantera generates to\nprocess \n&gt; CTI input files.  Judging from the pathname that appears in the\nerror \n&gt; message &quot;C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/&quot; it looks like you are\nrunning \n&gt; the demos from a directory with a long name, probably containing \n&gt; spaces.  Try copying the demos to a directory with a name that \n&gt; Windows/DOS does not mangle, or at least not as badly (short with\nno \n&gt; spaces). If that doesn&#39;t work, try running the temporary Python\nscript \n&gt; manually, and look for error messages - for example, type at a\ncommand \n&gt; prompt:\n&gt; \n&gt; python .check1100822275.pyw\n&gt; \n&gt; Hope this helps.\n&gt; \n&gt; Dave\n&gt; \n&gt; \n&gt; \n&gt; On Nov 18, 2004, at 5:47 PM, -Tom wrote:\n&gt; \n&gt; &gt;\n&gt; &gt;\n&gt; &gt; Group:\n&gt; &gt;\n&gt; &gt; I have attempted to install Cantera 1.5.4 (ver win32-py2.3) onto a\n&gt; &gt; WinXP Pro SP2 machine.  I also am using Matlab 7.0.1 and Python\n2.3.4\n&gt; &gt; w/Numeric-23.6.\n&gt; &gt;\n&gt; &gt; At this point, I am receiving &quot;Cantera Error!&quot; when I attempt to\nrun\n&gt; &gt; any of the demos.  I followed the Win installation directions and\nhave\n&gt; &gt; attempting several &quot;fixes&quot; to no success already.\n&gt; &gt;\n&gt; &gt; The error appears originate in the ct2ctml procedure.  The error\n&gt; &gt; indicators from both programs are listed below.\n&gt; &gt;\n&gt; &gt; Can anyone please offer any suggestion on how to address this\nerror?\n&gt; &gt;\n&gt; &gt; Thank you,\n&gt; &gt; -tom\n&gt; &gt;\n&gt; &gt;\n&gt; &gt; From Matlab---------Start Error---------------------\n&gt; &gt;\n&gt; &gt; The system cannot find the path specified.\n&gt; &gt; cmd /C c:/python23/python\n&gt; &gt; C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/.check1100822275.pyw&gt;&gt; log 2&gt;&1\n&gt; &gt; ##################################################\n&gt; &gt; ######################\n&gt; &gt; The Cantera Python interface is required in order to process\n&gt; &gt; Cantera input files, but it does not seem to be correctly\ninstalled.\n&gt; &gt; Check that you can invoke the Python interpreter with\n&gt; &gt; the command &quot;python&quot;, and that typing &quot;from Cantera import *&quot;\n&gt; &gt; at the Python prompt does not produce an error. If Python on your\n&gt; &gt; system\n&gt; &gt; is invoked with some other command, set environment variable\n&gt; &gt; PYTHON_CMD\n&gt; &gt; to the full path to the Python interpreter.\n&gt; &gt; ##################################################\n&gt; &gt; #######################\n&gt; &gt; ???\n&gt; &gt;\n&gt; &gt; ************************************************\n&gt; &gt;                 Cantera Error!\n&gt; &gt; ************************************************\n&gt; &gt;\n&gt; &gt;\n&gt; &gt; Procedure: ct2ctml\n&gt; &gt; Error:   could not convert input file to CTML\n&gt; &gt;  command line was: c:/python23/python\n&gt; &gt; C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/.cttmp1100822275.pyw&gt; ct2ctml.log\n2&gt;&1\n&gt; &gt; Error in Python installation\n&gt; &gt;\n&gt; &gt; Error in ==&gt; XML_Node.XML_Node at 11\n&gt; &gt;    x.id = ctmethods(10,15,0,src); % newxml(name)\n&gt; &gt;\n&gt; &gt; Error in ==&gt; Solution.Solution at 30\n&gt; &gt; doc = XML_Node(&#39;doc&#39;,src);\n&gt; &gt;\n&gt; &gt; Error in ==&gt; IdealGasMix at 39\n&gt; &gt;        s = Solution(a);\n&gt; &gt;\n&gt; &gt; Error in ==&gt; equil at 12\n&gt; &gt;    gas = IdealGasMix(&#39;gri30.cti&#39;);\n&gt; &gt;\n&gt; &gt; From Matlab:---------End Error---------------------\n&gt; &gt;\n&gt; &gt;\n&gt; &gt; From Python:------------Start Error--------------------\n&gt; &gt;&gt;&gt;&gt;\n&gt; &gt;  The system cannot find the path specified.\n&gt; &gt;\n&gt; &gt; cmd /C c:/python23/python C:&#92;DOCUME~1\n&gt; &gt; ps&#92;LOCALS~1&#92;Temp/.check1100822454.pyw&gt;&gt; log 2&gt;&1\n&gt; &gt;\n&gt; &gt; ##################################################\n&gt; &gt; ######################\n&gt; &gt;\n&gt; &gt; The Cantera Python interface is required in order to process\n&gt; &gt; Cantera input files, but it does not seem to be correctly\ninstalled.\n&gt; &gt;\n&gt; &gt; Check that you can invoke the Python interpreter with\n&gt; &gt; the command &quot;python&quot;, and that typing &quot;from Cantera import *&quot;\n&gt; &gt; at the Python prompt does not produce an error. If Python on your\n&gt; &gt; system\n&gt; &gt; is invoked with some other command, set environment variable\n&gt; &gt; PYTHON_CMD\n&gt; &gt; to the full path to the Python interpreter.\n&gt; &gt;\n&gt; &gt; ##################################################\n&gt; &gt; #######################\n&gt; &gt;\n&gt; &gt;\n&gt; &gt; Traceback (most recent call last):\n&gt; &gt;   File &quot;C:&#92;programs&#92;Cantera154&#92;demos&#92;Python&#92;mix1.py&quot;, line 25, in\n&gt; &gt; -toplevel-\n&gt; &gt;     gas_a = Air()\n&gt; &gt;   File &quot;C:&#92;programs&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;gases.py&quot;,\nline\n&gt; &gt; 40, in Air\n&gt; &gt;     return Solution(src=&quot;air.cti&quot;, id=&quot;air&quot;)\n&gt; &gt;   File &quot;C:&#92;programs&#92;Python23&#92;Lib&#92;site-packages\n&#92;Cantera&#92;solution.py&quot;,\n&gt; &gt; line 38, in __init__\n&gt; &gt;     root = XML.XML_Node(name = &#39;doc&#39;, src = src, preprocess = 1)\n&gt; &gt;   File &quot;C:&#92;programs&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;XML.py&quot;,\nline\n&gt; &gt; 35, in __init__\n&gt; &gt;     self._xml_id = _cantera.xml_get_XML_File(src)\n&gt; &gt; error:\n&gt; &gt;\n&gt; &gt; ************************************************\n&gt; &gt;                 Cantera Error!\n&gt; &gt; ************************************************\n&gt; &gt;\n&gt; &gt;\n&gt; &gt; Procedure: ct2ctml\n&gt; &gt; Error:   could not convert input file to CTML\n&gt; &gt;  command line was: c:/python23/python\n&gt; &gt; C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/.cttmp1100822454.pyw&gt; ct2ctml.log\n2&gt;&1\n&gt; &gt; Error in Python installation\n&gt; &gt;&gt;&gt;&gt;\n&gt; &gt;\n&gt; &gt; From Python:------------------End Error------------\n\n\n\n\n"}}