{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":44728387,"authorName":"David Goodwin","from":"David Goodwin &lt;dgoodwin@...&gt;","profile":"dggoodwin","replyTo":"LIST","senderId":"bfXPkmr_wsWzGoWN8oTl0eJVv1HJ3Y5aXCQQse73aT1SQn_o9Q3OhjTYPPzAjQx39OUC61HHn-X78---9myY8LfAM1M29Z2PEuib","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Re: [cantera] Re: ct2ctml error","postDate":"1100867285","msgId":591,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDc2QzRDNEY0LTNBMjYtMTFEOS05NkVCLTAwMEQ5M0FFMjQxQUBjYWx0ZWNoLmVkdT4=","inReplyToHeader":"PGNuazhpYythYmlnQGVHcm91cHMuY29tPg==","referencesHeader":"PGNuazhpYythYmlnQGVHcm91cHMuY29tPg=="},"prevInTopic":590,"nextInTopic":596,"prevInTime":590,"nextInTime":592,"topicId":588,"numMessagesInTopic":7,"msgSnippet":"Tom - The check script is run whenever the cttmp script fails, to see if the problem is with the Cantera installation.  Unfortunately the single-line","rawEmail":"Return-Path: &lt;dgoodwin@...&gt;\r\nX-Sender: dgoodwin@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 45087 invoked from network); 19 Nov 2004 12:28:26 -0000\r\nReceived: from unknown (66.218.66.216)\n  by m10.grp.scd.yahoo.com with QMQP; 19 Nov 2004 12:28:26 -0000\r\nReceived: from unknown (HELO outgoing-mail.its.caltech.edu) (131.215.49.69)\n  by mta1.grp.scd.yahoo.com with SMTP; 19 Nov 2004 12:28:26 -0000\r\nReceived: from earth-dog (earth-dog [192.168.1.3])\n\tby earth-ox-postvirus (Postfix) with ESMTP id 11B7B109DD6\n\tfor &lt;cantera@yahoogroups.com&gt;; Fri, 19 Nov 2004 04:28:14 -0800 (PST)\r\nReceived: from earth-ox ([192.168.1.9])\n\tby earth-dog (MailMonitor for SMTP v1.2.2 ) ;\n\tFri, 19 Nov 2004 04:28:13 -0800 (PST)\r\nReceived: from [10.0.1.2] (charter-241-015.caltech.edu [131.215.241.15])\n\tby earth-ox.its.caltech.edu (Postfix) with ESMTP id 9F501109B5B\n\tfor &lt;cantera@yahoogroups.com&gt;; Fri, 19 Nov 2004 04:28:12 -0800 (PST)\r\nMime-Version: 1.0 (Apple Message framework v619)\r\nIn-Reply-To: &lt;cnk8ic+abig@...&gt;\r\nReferences: &lt;cnk8ic+abig@...&gt;\r\nContent-Type: text/plain; charset=US-ASCII; format=flowed\r\nMessage-Id: &lt;76C4C4F4-3A26-11D9-96EB-000D93AE241A@...&gt;\r\nContent-Transfer-Encoding: 7bit\r\nDate: Fri, 19 Nov 2004 04:28:05 -0800\r\nTo: cantera@yahoogroups.com\r\nX-Mailer: Apple Mail (2.619)\r\nX-Spam-Status: No, hits=0.0 tagged_above=-100000.0 required=5.0 \r\nX-Spam-Level: \r\nX-eGroups-Remote-IP: 131.215.49.69\r\nFrom: David Goodwin &lt;dgoodwin@...&gt;\r\nSubject: Re: [cantera] Re: ct2ctml error\r\nX-Yahoo-Group-Post: member; u=44728387\r\nX-Yahoo-Profile: dggoodwin\r\n\r\nTom -\n\nThe &#39;check&#39; script is run whenever the &#39;cttmp&#39; script fails, to see if \nthe problem is with the Cantera installation.  Unfortunately the \nsingle-line &#39;check&#39; script will always fail, since it tries to import \nmodule &#39;ctml_writer&#39; from the Cantera package  (where it used to be), \ninstead of importing it directly.  The workaround is to copy file \n&#39;ctml_writer.py&#39; from the &#39;site_packages&#39; folder in the Python Library \nfolder to the &#39;Cantera&#39; folder within &#39;site_packages&#39;.   it seems to me \nnow that running the &#39;check&#39; script is more trouble than it is worth, \nand I am removing this step from the procedure followed to translate \ninput files.\n\nBut this does not answer why the cttmp script fails, since it works \nwhen you run it from the command line.  I&#39;m not sure why that is \nhappening, but it must be some sort of path problem.  Perhaps try the \nabove fix and try again and see what happens...\n\nBy the way - I assume you are using WinXP or Win2000.  Cantera will \nencounter problems under Win98 or WinME.\n\nDave\n\n\nOn Nov 18, 2004, at 11:49 PM, -Tom wrote:\n\n&gt;\n&gt;\n&gt; Dr. Goodwin:\n&gt;\n&gt; Thank you for your prompt response.\n&gt;\n&gt; After review of your suggestion I investigated further.  The path\n&gt; specified in the error is not governed by the location of the demo\n&gt; files, but rather the location of my active temporary file.  This is\n&gt; set by the OS Environment Variables.  That said, I changed my TEMP\n&gt; variables to point to c:&#92;tmpdir instead of in my long named profile\n&gt; directory.  However, this did not correct the error.\n&gt;\n&gt; In which ever temp directory is specified there are 2 files generated\n&gt; before the error stops the program.   They are:\n&gt; .cttmp1100848520.pyw\n&gt; .check1100848520.pyw\n&gt; The the contents and resulta of attempting to run these files is show\n&gt; below.  The .cttmp##.pyw file will successfully generate the file\n&gt; gri30.xml when initiated by the cmd prompt.   However the .check##.pyw\n&gt; errors out.\n&gt;\n&gt; Are there additional steps I should attempt towards resolving this\n&gt; issue?\n&gt;\n&gt; I appreaciate your assistance.\n&gt;\n&gt; -tom\n&gt;\n&gt; ---Running gennerated files from DOS prompt --------start----------\n&gt; Microsoft Windows XP [Version 5.1.2600]\n&gt; (C) Copyright 1985-2001 Microsoft Corp.\n&gt;\n&gt; C:&#92;Documents and Settings&#92;tps&gt;python c:&#92;tmpdir&#92;.cttmp1100848520.pyw\n&gt;\n&gt; C:&#92;Documents and Settings&#92;tps&gt;python c:&#92;tmpdir&#92;.check1100848520.pyw\n&gt; Traceback (most recent call last):\n&gt;   File &quot;c:&#92;tmpdir&#92;.check1100848520.pyw&quot;, line 1, in ?\n&gt;     from Cantera import ctml_writer\n&gt; ImportError: cannot import name ctml_writer\n&gt;\n&gt; C:&#92;Documents and Settings&#92;tps&gt;\n&gt; ----Running gennerated files from DOS prompt -----------end----------\n&gt;\n&gt; -------- Contents of .cttmp1100848520.pyw -----------------\n&gt; from ctml_writer import *\n&gt; import sys, os, os.path\n&gt; file = &quot;C:&#92;Program Files&#92;Common Files/Cantera/data/gri30.cti&quot;\n&gt; base = os.path.basename(file)\n&gt; root, ext = os.path.splitext(base)\n&gt; dataset(root)\n&gt; execfile(file)\n&gt; write()\n&gt; -------------end .cttmp1100848520.pyw --------------------\n&gt;\n&gt; ------- Contents of .check1100848520.pyw -------------\n&gt; from Cantera import ctml_writer\n&gt; ------------End .check1100848520.pyw-------------------\n&gt;\n&gt;\n&gt;\n&gt; --- In cantera@yahoogroups.com, David Goodwin &lt;dgoodwin@c...&gt; wrote:\n&gt;&gt; Tom - I&#39;m not sure, but if I were to guess, I would guess that\n&gt; Python\n&gt;&gt; is not finding the temporary Python script Cantera generates to\n&gt; process\n&gt;&gt; CTI input files.  Judging from the pathname that appears in the\n&gt; error\n&gt;&gt; message &quot;C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/&quot; it looks like you are\n&gt; running\n&gt;&gt; the demos from a directory with a long name, probably containing\n&gt;&gt; spaces.  Try copying the demos to a directory with a name that\n&gt;&gt; Windows/DOS does not mangle, or at least not as badly (short with\n&gt; no\n&gt;&gt; spaces). If that doesn&#39;t work, try running the temporary Python\n&gt; script\n&gt;&gt; manually, and look for error messages - for example, type at a\n&gt; command\n&gt;&gt; prompt:\n&gt;&gt;\n&gt;&gt; python .check1100822275.pyw\n&gt;&gt;\n&gt;&gt; Hope this helps.\n&gt;&gt;\n&gt;&gt; Dave\n&gt;&gt;\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; On Nov 18, 2004, at 5:47 PM, -Tom wrote:\n&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt; Group:\n&gt;&gt;&gt;\n&gt;&gt;&gt; I have attempted to install Cantera 1.5.4 (ver win32-py2.3) onto a\n&gt;&gt;&gt; WinXP Pro SP2 machine.  I also am using Matlab 7.0.1 and Python\n&gt; 2.3.4\n&gt;&gt;&gt; w/Numeric-23.6.\n&gt;&gt;&gt;\n&gt;&gt;&gt; At this point, I am receiving &quot;Cantera Error!&quot; when I attempt to\n&gt; run\n&gt;&gt;&gt; any of the demos.  I followed the Win installation directions and\n&gt; have\n&gt;&gt;&gt; attempting several &quot;fixes&quot; to no success already.\n&gt;&gt;&gt;\n&gt;&gt;&gt; The error appears originate in the ct2ctml procedure.  The error\n&gt;&gt;&gt; indicators from both programs are listed below.\n&gt;&gt;&gt;\n&gt;&gt;&gt; Can anyone please offer any suggestion on how to address this\n&gt; error?\n&gt;&gt;&gt;\n&gt;&gt;&gt; Thank you,\n&gt;&gt;&gt; -tom\n&gt;&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt; From Matlab---------Start Error---------------------\n&gt;&gt;&gt;\n&gt;&gt;&gt; The system cannot find the path specified.\n&gt;&gt;&gt; cmd /C c:/python23/python\n&gt;&gt;&gt; C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/.check1100822275.pyw&gt;&gt; log 2&gt;&1\n&gt;&gt;&gt; ##################################################\n&gt;&gt;&gt; ######################\n&gt;&gt;&gt; The Cantera Python interface is required in order to process\n&gt;&gt;&gt; Cantera input files, but it does not seem to be correctly\n&gt; installed.\n&gt;&gt;&gt; Check that you can invoke the Python interpreter with\n&gt;&gt;&gt; the command &quot;python&quot;, and that typing &quot;from Cantera import *&quot;\n&gt;&gt;&gt; at the Python prompt does not produce an error. If Python on your\n&gt;&gt;&gt; system\n&gt;&gt;&gt; is invoked with some other command, set environment variable\n&gt;&gt;&gt; PYTHON_CMD\n&gt;&gt;&gt; to the full path to the Python interpreter.\n&gt;&gt;&gt; ##################################################\n&gt;&gt;&gt; #######################\n&gt;&gt;&gt; ???\n&gt;&gt;&gt;\n&gt;&gt;&gt; ************************************************\n&gt;&gt;&gt;                 Cantera Error!\n&gt;&gt;&gt; ************************************************\n&gt;&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt; Procedure: ct2ctml\n&gt;&gt;&gt; Error:   could not convert input file to CTML\n&gt;&gt;&gt;  command line was: c:/python23/python\n&gt;&gt;&gt; C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/.cttmp1100822275.pyw&gt; ct2ctml.log\n&gt; 2&gt;&1\n&gt;&gt;&gt; Error in Python installation\n&gt;&gt;&gt;\n&gt;&gt;&gt; Error in ==&gt; XML_Node.XML_Node at 11\n&gt;&gt;&gt;    x.id = ctmethods(10,15,0,src); % newxml(name)\n&gt;&gt;&gt;\n&gt;&gt;&gt; Error in ==&gt; Solution.Solution at 30\n&gt;&gt;&gt; doc = XML_Node(&#39;doc&#39;,src);\n&gt;&gt;&gt;\n&gt;&gt;&gt; Error in ==&gt; IdealGasMix at 39\n&gt;&gt;&gt;        s = Solution(a);\n&gt;&gt;&gt;\n&gt;&gt;&gt; Error in ==&gt; equil at 12\n&gt;&gt;&gt;    gas = IdealGasMix(&#39;gri30.cti&#39;);\n&gt;&gt;&gt;\n&gt;&gt;&gt; From Matlab:---------End Error---------------------\n&gt;&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt; From Python:------------Start Error--------------------\n&gt;&gt;&gt;&gt;&gt;&gt;\n&gt;&gt;&gt;  The system cannot find the path specified.\n&gt;&gt;&gt;\n&gt;&gt;&gt; cmd /C c:/python23/python C:&#92;DOCUME~1\n&gt;&gt;&gt; ps&#92;LOCALS~1&#92;Temp/.check1100822454.pyw&gt;&gt; log 2&gt;&1\n&gt;&gt;&gt;\n&gt;&gt;&gt; ##################################################\n&gt;&gt;&gt; ######################\n&gt;&gt;&gt;\n&gt;&gt;&gt; The Cantera Python interface is required in order to process\n&gt;&gt;&gt; Cantera input files, but it does not seem to be correctly\n&gt; installed.\n&gt;&gt;&gt;\n&gt;&gt;&gt; Check that you can invoke the Python interpreter with\n&gt;&gt;&gt; the command &quot;python&quot;, and that typing &quot;from Cantera import *&quot;\n&gt;&gt;&gt; at the Python prompt does not produce an error. If Python on your\n&gt;&gt;&gt; system\n&gt;&gt;&gt; is invoked with some other command, set environment variable\n&gt;&gt;&gt; PYTHON_CMD\n&gt;&gt;&gt; to the full path to the Python interpreter.\n&gt;&gt;&gt;\n&gt;&gt;&gt; ##################################################\n&gt;&gt;&gt; #######################\n&gt;&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt; Traceback (most recent call last):\n&gt;&gt;&gt;   File &quot;C:&#92;programs&#92;Cantera154&#92;demos&#92;Python&#92;mix1.py&quot;, line 25, in\n&gt;&gt;&gt; -toplevel-\n&gt;&gt;&gt;     gas_a = Air()\n&gt;&gt;&gt;   File &quot;C:&#92;programs&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;gases.py&quot;,\n&gt; line\n&gt;&gt;&gt; 40, in Air\n&gt;&gt;&gt;     return Solution(src=&quot;air.cti&quot;, id=&quot;air&quot;)\n&gt;&gt;&gt;   File &quot;C:&#92;programs&#92;Python23&#92;Lib&#92;site-packages\n&gt; &#92;Cantera&#92;solution.py&quot;,\n&gt;&gt;&gt; line 38, in __init__\n&gt;&gt;&gt;     root = XML.XML_Node(name = &#39;doc&#39;, src = src, preprocess = 1)\n&gt;&gt;&gt;   File &quot;C:&#92;programs&#92;Python23&#92;Lib&#92;site-packages&#92;Cantera&#92;XML.py&quot;,\n&gt; line\n&gt;&gt;&gt; 35, in __init__\n&gt;&gt;&gt;     self._xml_id = _cantera.xml_get_XML_File(src)\n&gt;&gt;&gt; error:\n&gt;&gt;&gt;\n&gt;&gt;&gt; ************************************************\n&gt;&gt;&gt;                 Cantera Error!\n&gt;&gt;&gt; ************************************************\n&gt;&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt; Procedure: ct2ctml\n&gt;&gt;&gt; Error:   could not convert input file to CTML\n&gt;&gt;&gt;  command line was: c:/python23/python\n&gt;&gt;&gt; C:&#92;DOCUME~1&#92;tps&#92;LOCALS~1&#92;Temp/.cttmp1100822454.pyw&gt; ct2ctml.log\n&gt; 2&gt;&1\n&gt;&gt;&gt; Error in Python installation\n&gt;&gt;&gt;&gt;&gt;&gt;\n&gt;&gt;&gt;\n&gt;&gt;&gt; From Python:------------------End Error------------\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n&gt; Yahoo! Groups Links\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n&gt;\n\n\n\n"}}