{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":226475284,"authorName":"Scott","from":"&quot;Scott&quot; &lt;thawdog@...&gt;","profile":"thawdog","replyTo":"LIST","senderId":"BlulVuQ8QJ7V141x9VddkeNPHdcdWwlY9CkZIIC4pLHd-afay8d0eMUSz5b22zuZmJ9VfcdyBoSYK9qXmokhtzRq","spamInfo":{"isSpam":false,"reason":"12"},"subject":"1.5.5 windows binary install problems","postDate":"1117842890","msgId":829,"canDelete":false,"contentTrasformed":false,"systemMessage":true,"headers":{"messageIdInHeader":"PGQ3cXFrYSs0Njl1QGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":830,"prevInTime":828,"nextInTime":830,"topicId":829,"numMessagesInTopic":2,"msgSnippet":"I have installed python/cantera.  When I try to run one of the python demos I get the error message: This application has failed to start because MSVCP71.dll","rawEmail":"Return-Path: &lt;thawdog@...&gt;\r\nReceived: (qmail 38787 invoked from network); 4 Jun 2005 02:07:18 -0000\r\nReceived: from unknown (66.218.66.217)\n  by m26.grp.scd.yahoo.com with QMQP; 4 Jun 2005 02:07:18 -0000\r\nReceived: from unknown (HELO n8.bulk.dcn.yahoo.com) (216.155.201.61)\n  by mta2.grp.scd.yahoo.com with SMTP; 4 Jun 2005 02:07:18 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [216.155.201.65] by n8.bulk.dcn.yahoo.com with NNFMP; 04 Jun 2005 02:07:17 -0000\r\nReceived: from [66.218.69.1] by mailer2.bulk.dcn.yahoo.com with NNFMP; 04 Jun 2005 02:07:17 -0000\r\nReceived: from [66.218.66.74] by mailer1.bulk.scd.yahoo.com with NNFMP; 04 Jun 2005 02:07:17 -0000\r\nX-Sender: thawdog@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 75048 invoked from network); 3 Jun 2005 23:55:04 -0000\r\nReceived: from unknown (66.218.66.167)\n  by m23.grp.scd.yahoo.com with QMQP; 3 Jun 2005 23:55:04 -0000\r\nReceived: from unknown (HELO n24.bulk.scd.yahoo.com) (66.94.237.53)\n  by mta6.grp.scd.yahoo.com with SMTP; 3 Jun 2005 23:55:04 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [66.218.69.3] by n24.bulk.scd.yahoo.com with NNFMP; 03 Jun 2005 23:54:51 -0000\r\nReceived: from [66.218.66.86] by mailer3.bulk.scd.yahoo.com with NNFMP; 03 Jun 2005 23:54:51 -0000\r\nDate: Fri, 03 Jun 2005 23:54:50 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;d7qqka+469u@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 838\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-system\r\nX-eGroups-Msg-Info: 1:12:0\r\nFrom: &quot;Scott&quot; &lt;thawdog@...&gt;\r\nSubject: 1.5.5 windows binary install problems\r\nX-Yahoo-Group-Post: member; u=226475284; y=8ukyII3mwjKQ92rUs4xsesi0g7pquMqfkDk8-N8N-UmzgA\r\nX-Yahoo-Profile: thawdog\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 04 Jun 2005 02:07:15 -0000\r\n\r\nI have installed python/cantera.  When I try to run one of the \npython demos I get the error message:\n\nThis application has failed to start because MSVCP71.dll was not \nfoudn. Re-installing the application may fix this problem.\n\nThe error message I get if I run from IDLE is:\n\nTraceback (most recent call last):\n  File &quot;C:&#92;Cantera&#92;demos&#92;Python&#92;flame1.py&quot;, line 7, in ?\n    from Cantera import *\n  File &quot;C:&#92;Python24&#92;Lib&#92;site-packages&#92;Cantera&#92;__init__.py&quot;, line 8, \nin ?\n    from exceptions import *\n  File &quot;C:&#92;Python24&#92;Lib&#92;site-packages&#92;Cantera&#92;exceptions.py&quot;, line \n5, in ?\n    import _cantera\nImportError: DLL load failed: The specified module could not be \nfound.\n\n\nI&#39;ve reinstalled both python and cantera but this error still \npersists.  Also, there error doesn&#39;t appear when I open up mixmaster.\nDo you have any suggestions?\n\nScott \n\n\n\n\n\n\n"}}